### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by skarelin** [redstone-finance/redstone-academy#25]
Link: https://redstone.academy/docs/pst/writing-pst-contract/preparations

I had a problem with running the yarn command. Shouldn't it be `arweave@1.10.19` ?

**Comment by skarelin** [comment]
Link: https://redstone.academy/docs/pst/writing-pst-contract/contract-source

Section "Read":
`PstResult` looks redundant (also, I do not see it in the final version)

**Comment by asiaziola** [comment]
> Link: https://redstone.academy/docs/pst/writing-pst-contract/preparations
> 
> I had a problem with running the yarn command. Shouldn't it be `arweave@1.10.19` ?

Issue has been fixed within this pr https://github.com/redstone-finance/redstone-academy/pull/26.
All the smartweave based libs have been upgraded.

**Comment by ppedziwiatr** [comment]
closing.
